### ISSUE TITLE
License summary display improvement

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#222]
The license summary still needs some attention. Currently it just has question marks that aren't clearly marked as buttons. When you click them, extra text is displayed, but the formatting is a bit off. The '?'s are confusing and now do not do anything; in previous versions they linked additional info.

**Comment by sosguthorpe** [comment]
Bug with the info popups needs fixing.

Think we may need a discussion about what can be done about the layout.

**Comment by ianibo** [comment]
This has escalated a little from "Can we use the onix xsl to format a license and display for selden" to a slightly larger task. The XSL output is a poor fit for GOKb and each update to the UI causes many problems with trying to fix the output of this XSL. We propose, if this feature is really needed, to import the Onix display work from KB+. Steve to discuss in call.

**Comment by kristenwilson** [comment]
For 4.0, just fix question marks, don't worry about any other UI stuff.

**Comment by iyawnis** [comment]
Fixed icons, and click for extra details. 
![screenshot from 2015-02-06 14 43 45](https://cloud.githubusercontent.com/assets/2336352/6081095/ab6cbaee-ae0e-11e4-8dd1-45f1fd2f2837.png)

**Comment by iyawnis** [comment]
To make the above effective, it requires to Regenerate License Summaries from admin menu.

**Comment by kristenwilson** [comment]
My screen does not look like the screenshot Ioannis pasted above. I'm still seeing the old text question marks that are not editable.

**Comment by iyawnis** [comment]
I kicked off Regenerate License Summaries and it works now. This is visible only on one licence:
https://gokb.k-int.com/gokb/resource/show/org.gokb.cred.License%3A37763 

This is because the xml file are missing for the other licence, therefore cant generate the summary.

**Comment by kristenwilson** [comment]
Confirmed that this is working.
