### ISSUE TITLE
No Review Task being created on partial/good TI matches

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#28]
When an ingested line gives a good or partial match on TI based on ID matching, should use the match found (this works), add incoming publicationtitle string as Alternative Title if required (this works) and create a review task for the TIPP

This last step doesn't seem to work, or at least I'm seeing no Review Requests in http://gokb.k-int.com/gokb/search/index?qbe=g%3AreviewRequests

I'd expect to based on the Good/Partial match TIPPs loaded against this TI http://gokb.k-int.com/gokb/search/index?qbe=g%3Atitles&qp_name=Ambix%25&det=1 - which resulted in alternative TI strings being added

**Comment by ianibo** [comment]
THink this is the not null rr_timestamp column in the DB... Hopefully resolved by dropping that col.

**Comment by ostephens** [comment]
Just re-tested and still a problem I think. See http://gokb.k-int.com/gokb/resource/show/org.gokb.cred.TitleInstance%3A33047 - just ingested with Alternative Title successfully but no Review Task created

**Comment by ianibbo** [comment]
Got this in DB.. does it look related?

```
 1 |       0 |                  33032 | 2013-08-19 19:08:07 | Publisher
```

supplied in ingested file is different to any already present on TI. |
2013-08-19 19:08:07 | Added 'Maney Publishing' as a publisher on 'Ambix:
 The Journal of the Society for the History of Alchemy and Chemistry'. |
    337 |         NULL |           NULL |

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment]
I'm afraid not - that's for a different test - that's the correctly created Review Request when adding additional publisher (see https://github.com/k-int/gokb-phase1/issues/33 - now working correctly)

**Comment by ostephens** [comment]
Good titles matches should not create Review Requests (my bad)
Partial title match now creating Review Request correctly
